export const CONVERSATION_TYPE_COMMENT_FB = 1;
export const CONVERSATION_TYPE_CHAT_FB = 2;

export const CONVERSATION_IS_READ = 1;
export const CONVERSATION_IS_NOT_READ = 0;

export const CONVERSATION_TYPE_MEDIA_IMAGE = 1;
export const CONVERSATION_TYPE_MEDIA_VIDEO = 2;
export const CONVERSATION_MEDIA_SOURCE_POST = 1;
export const CONVERSATION_MEDIA_SOURCE_ENGAGE = 2;